# Generated by Django 3.2.7 on 2021-09-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcelist',
            old_name='resourcedescription',
            new_name='resource_description',
        ),
    ]
